#!/usr/bin/env python

import os
import sys
import apt
from user import home
import gettext
import gtk

# i18n
gettext.install("solydxk-softwaremanager", "/usr/share/locale")

os.system("mkdir -p " + home + "/.solydxk/softwaremanager/tmp")
os.system("rm -rf " + home + "/.solydxk/softwaremanager/tmp/*")
os.chdir(home + "/.solydxk/softwaremanager/tmp")
pkg_name = sys.argv[1]

try:
    cache = apt.Cache()
    pkg = cache[pkg_name]
    description = pkg.summary
    size = pkg.packageSize
    size = int(size / 1000000)
    os.mkdir(pkg_name)
    os.chdir(pkg_name)
    os.system("echo \"" + pkg_name + "\" > name")
    os.system("echo \"" + description + "\" > description")
    os.mkdir("steps")
    os.chdir("steps")
    os.system("echo \"TITLE Installing " + pkg_name + "\" > 1")
    os.system("echo \"INSTALL " + pkg_name + "\" >> 1")
    os.chdir(home + "/.solydxk/softwaremanager/tmp")
    os.system("/usr/lib/solydxk/softwaremanager/compress " + pkg_name)
    os.system("rm -rf " + pkg_name)
    os.system("softwaremanager " + pkg_name + ".swm")
except Exception, cause:
    print _("Could not find package: %s") % pkg_name
    msgDlg = gtk.MessageDialog( None, gtk.DIALOG_MODAL, gtk.MESSAGE_ERROR, gtk.BUTTONS_OK, _("Could not find package: %s") % pkg_name )
    msgDlg.set_title("softwaremanager")
    msgDlg.set_icon_from_file("/usr/share/solydxk/logo.png")
    msgDlg.run();
    msgDlg.destroy();
